name: Build and check links

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - name: Build
        run: |        
          sudo gem install bundler
          bundle update
          make build
          
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - name: Check links
        run: |      
          sudo gem install bundler
          bundle install
          make check_links
        
